import { StyleSheet } from 'react-native';
import { SCREEN_WIDTH, SCREEN_HEIGHT } from '../../utils/constants';
import { moderateScale, scale, verticalScale } from '../../utils/styles/responsive';
import Colors from '../../utils/styles/colors';

export default StyleSheet.create({
  alignItemStart: {
    alignItems: 'flex-start',
  },
  alignItemsCenter: {
    alignItems: 'center',
    top: '18.5%',
  },
  backIcon: {
    height: verticalScale(42),
    marginTop: verticalScale(0),
    tintColor: Colors.BLUE_0,
    width: moderateScale(42),
  },
  backdrop: {
    backgroundColor: Colors.BACKDROP_COLOR,
    height: SCREEN_HEIGHT - 24,
    width: '100%',
    ...StyleSheet.absoluteFillObject,
  },
  buttonBack: {
    height: 38,
    marginLeft: verticalScale(24),
    marginTop: verticalScale(24),
    width: 38,
  },
  cellStyle: {
    borderBottomWidth: 3,
    borderColor: Colors.BLUE_0,
  },
  cellStyleFocused: {
    borderBottomWidth: 4,
    borderColor: Colors.BLUE_0,
  },
  centeredRow: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  checkEmailText: {
    color: Colors.GRAY_40,
    fontSize: moderateScale(15, 0.3),
    textAlign: 'center',
  },
  container: {
    backgroundColor: Colors.GREY,
    flexGrow: 1,
    height: '100%',
  },
  containerCodeInputs: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  containerForgotPass: {
    height: '100%',
    paddingHorizontal: scale(30),
    paddingVertical: 20,
    width: '100%',
  },
  containerOpacity: {
    opacity: 0.5,
  },
  containerResendCode: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: verticalScale(30),
  },
  containerTextTimer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: moderateScale(35),
  },
  forgotPass: {
    color: Colors.BLUE_DEEP_0,
    fontSize: moderateScale(30, 0.3),
    lineHeight: verticalScale(40),
    marginVertical: verticalScale(20),
  },
  forgotPassCode: {
    color: Colors.BLACK,
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: 1,
    lineHeight: 30,
    marginVertical: 15,
  },
  forgotPassReset: {
    color: Colors.BLACK,
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: 1,
    lineHeight: 30,
    marginTop: 15,
    marginVertical: 20,
  },
  formContainer: {
    flex: 1,
    paddingBottom: verticalScale(100),
    paddingHorizontal: scale(20),
    paddingVertical: verticalScale(10),
  },
  headerText: {
    color: Colors.BLACK,
    fontSize: 25,
    fontWeight: 'bold',
    margin: 10,
    textAlign: 'center',
  },
  inputError: {
    color: Colors.RED,
    fontSize: moderateScale(14, 0.2),
    marginBottom: verticalScale(10),
    marginTop: verticalScale(8),
    paddingLeft: scale(16),
  },
  inputErrorMessage: {
    color: Colors.RED,
    fontSize: moderateScale(14, 0.3),
    marginLeft: scale(12),
    marginTop: verticalScale(10),
  },
  inputResendCodeContainer: {
    alignItems: 'center',
    marginTop: 25,
  },
  inputTxt: (empty, error) => ({
    backgroundColor: Colors.WHITE,
    borderRadius: moderateScale(30),
    color: Colors.GRAY_40,
    fontSize: moderateScale(16),
    height: moderateScale(60),
    paddingHorizontal: scale(20),
    borderWidth: empty ? 1 : 2,
    borderColor: error ? Colors.RED : Colors.BLUE_0,
  }),
  inputTxtNumeric: {
    color: Colors.GRAY_0,
    fontSize: moderateScale(18, 0.3),
  },
  instructions: {
    color: Colors.GRAY_10,
    fontSize: moderateScale(16, 0.3),
    lineHeight: verticalScale(25),
    marginBottom: verticalScale(30),
    marginTop: verticalScale(10),
  },
  instructionsOtpScreen: {
    color: Colors.GRAY_40,
    fontSize: moderateScale(16, 0.3),
    lineHeight: verticalScale(25),
    marginBottom: verticalScale(30),
    marginTop: verticalScale(10),
  },
  keyboardAboding: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
  },
  label: {
    color: Colors.BLUE_DEEP_0,
    fontSize: moderateScale(16, 0.2),
    marginBottom: 8,
    paddingLeft: scale(16),
  },
  logoMomentoPosition: {
    alignItems: 'center',
    height: verticalScale(40),
    top: verticalScale(100),
    width: SCREEN_WIDTH,
  },
  messageInputPasswordColor: {
    color: Colors.SKY_BLUE,
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '600',
  },
  modalBodyRadiusCode: {
    backgroundColor: Colors.WHITE,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    bottom: 0,
    minHeight: verticalScale(336),
    width: '100%',
  },
  modalBodyRadiusCodeEmailProvide: {
    backgroundColor: Colors.WHITE,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    bottom: 0,
    minHeight: verticalScale(336),
    overflow: "hidden",
    position: "absolute",
    width: "100%",
  },
  modalBodyRadiusOtpContainer: {
    backgroundColor: Colors.WHITE,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    bottom: 0,
    minHeight: verticalScale(336),
    overflow: "hidden",
    position: "absolute",
    width: "100%",
  },
  modalBodyRadiusReset: {
    backgroundColor: Colors.WHITE,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    top: '35%',
  },
  modalBodyRadiusSignIn: {
    backgroundColor: Colors.WHITE,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    margin: 0,
    top: SCREEN_HEIGHT / 4,
    width: '100%',
  },
  modalContainerStyle: {
    paddingBottom: verticalScale(0),
    paddingTop: verticalScale(30),
  },
  modalContainerSuccessStyle: {
    paddingBottom: verticalScale(20),
    paddingTop: verticalScale(30),
  },
  passwordInputIcon: {
    right: moderateScale(12),
  },
  passwordRulesDescription: {
    fontSize: moderateScale(15, 0.3),
    lineHeight: verticalScale(22),
    marginTop: verticalScale(-10),
    textAlign: 'left',
  },
  questionIcon: {
    bottom: verticalScale(3),
    height: verticalScale(20),
    left: moderateScale(5),
    tintColor: Colors.CORAL_0,
    width: moderateScale(20),
  },
  rememberMe: {
    color: Colors.GREY_MEDIUM,
    fontSize: 16,
    letterSpacing: 0.25,
  },
  resendCodeText: {
    color: Colors.CORAL_0,
    fontSize: scale(15, 0.8),
    textDecorationLine: 'underline',
  },
  resendCodeTextDisabled: {
    color: Colors.LEAD,
    fontSize: scale(13),
  },
  resendCodeTextTime: {
    color: Colors.GRAY_0,
    fontSize: scale(15, 0.8),
  },
  scrollContainer: {
    minHeight: '100%',
  },
  signInEnterContainer: {
    alignItems: 'center',
    color: Colors.GREY_MEDIUM,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    lineHeight: 50,
    marginVertical: 25,
  },
  signInForgotPasswordContatiner: {
    alignItems: 'center',
    marginTop: 15,
  },
  signInForgotPasswordText: {
    color: Colors.GREY_MEDIUM,
    fontSize: 14,
    letterSpacing: 0.6,
    textDecorationLine: 'underline',
  },
  signInIconForward: {
    height: 40,
    width: 40,
  },
  signInIconForwardContainer: {
    alignItems: 'center',
    backgroundColor: Colors.GREEN,
    borderRadius: 100,
    height: 50,
    justifyContent: 'center',
    marginLeft: 10,
    padding: 20,
    width: 50,
  },
  signInLoginText: {
    color: Colors.GREY_MEDIUM,
    fontSize: 26,
    fontWeight: '700',
    letterSpacing: 0.25,
  },
  signIntextBox: {
    alignSelf: 'stretch',
    borderBottomColor: Colors.GREEN,
    borderBottomWidth: 1,
    color: Colors.GREY,
    fontSize: 16,
    height: 40,
    letterSpacing: 1,
    lineHeight: 20,
    marginVertical: 10,
    paddingLeft: 8,
    paddingRight: 45,
  },
  submitButton: {
    borderRadius: moderateScale(100),
    height: verticalScale(55),
    width: scale(200),
  },
  successIcon: {
    height: scale(80),
    tintColor: Colors.BLUE_0,
    width: scale(80),
  },
  successPasswordDescriptionContainer: {
    alignItems: 'center',
  },
  successPasswordDescriptionText: {
    color: Colors.GRAY_10,
    fontSize: moderateScale(16, 0.5),
    lineHeight: verticalScale(22),
    marginTop: verticalScale(10),
    textAlign: 'center',
  },
  textBox: (empty, error) => ({
    backgroundColor: Colors.WHITE,
    borderWidth: empty ? 1 : 2,
    borderColor: error ? Colors.RED : Colors.BLUE_0,
    borderRadius: 30,
    color: Colors.GRAY_40,
    fontSize: moderateScale(16),
    height: moderateScale(60),
    paddingHorizontal: scale(20),
  }),
  textBoxContainer: {
    alignSelf: 'stretch',
    justifyContent: 'center',
    position: 'relative',
  },
  textBtnNext: {
    color: Colors.WHITE,
    fontSize: 16,
    fontWeight: '600',
  },
  textOtpTarget: {
    color: Colors.BLUE_0,
  },
  textResendDisabled: {
    color: Colors.GRAY_0,
    fontSize: scale(15, 0.9),
  },
  toolbar: {
    marginLeft: verticalScale(16),
    marginTop: verticalScale(9),
  },
  touchableBackdrop: {
    height: SCREEN_HEIGHT - 24,
    width: '100%',
  },
  touchableButton: {
    height: verticalScale(30),
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    right: scale(5),
    width: verticalScale(30),
  },
  verifyButton: {
    alignSelf: 'center',
    borderRadius: moderateScale(100),
    height: verticalScale(54),
    marginTop: verticalScale(65),
    maxWidth: scale(200),
    width: '100%',
  },
});
