name: Expo Publish Production

on:
  push:
    branches:
      - main

env:
  NODE_ENV: ${{ 'production' }}
  API_URL: ${{ secrets.API_URL }}
  ACCESS_USER_KEY: ${{ secrets.ACCESS_USER_KEY }}

jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          username: ${{ secrets.EXPO_CLI_USERNAME }}
          password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: expo publish --release-channel toolbox-challenge
